Add blue ocean
alfg/opendrinks pull request #1317
Opened 2022-10-05 18:02 UTC by patprodrigues

add new recipe

2022-10-20 10:38 UTC, patprodrigues commented
@alfg Hi just to check if someone can check and approve this.

2022-10-27 06:45 UTC, alfg commented on bue-ocean.json
> +        "..."
What is this for?

2022-10-27 06:45 UTC, alfg requested changes
Please resize image and re-submit.

2022-10-27 06:45 UTC, alfg commented on bue-ocean.json
> +    "github": "<patprodrigues",
Just the username here.

2022-10-29 17:08 UTC, patprodrigues commented
@alfg fixed, thank you.

2022-11-28 08:15 UTC, closed without merging