add crazy lactobacilly recipe and drink picture
alfg/opendrinks pull request #1356
Opened 2022-10-27 22:07 UTC by marjorinec

2022-10-28 04:29 UTC, alfg requested changes
Possible to use an image 600x400 in size?

2022-10-28 14:27 UTC, marjorinec commented
done!

2022-10-31 17:46 UTC, marjorinec commented
@alfg  hey, can you review my pr?

2022-11-02 04:24 UTC, alfg commented
The drink in the image seems cropped out.

2022-11-28 08:15 UTC, closed without merging