Create easy-sangria.json
alfg/opendrinks pull request #721
Opened 2020-09-30 16:33 UTC by xtbe

Add recipe for easy Sangria

2020-10-01 00:57 UTC, alfg requested changes

2020-10-01 00:57 UTC, alfg commented on src/recipes/easy-sangria.json
> +    "image": "sangria-new-crop-8fbb7a1.jpg",
Hi, thanks for the PR. It seems the image is missing. Also, can you rename this image to match the json filename too? `easy-sangria.jpg`. Thank you!

2020-10-01 17:30 UTC, alfg commented on src/recipes/easy-sangria.json
> +    "image": "sangria-new-crop-8fbb7a1.jpg",
Hi, the image still seems to be missing. Can you add it in?

2020-10-01 17:33 UTC, xtbe commented
Hm must have done something wrong then, I do see my second commit... which should fix the image...

2020-10-04 19:58 UTC, alfg commented
Closing. Feel free to re-open with fixed image. Thanks!

2020-10-04 19:58 UTC, closed without merging

2020-10-04 20:02 UTC, xtbe commented
I added the missing image in a 2nd commit. Did I do something wrong in contingent the fix for this?

2020-10-04 20:04 UTC, alfg commented
Hi @xtbe, I see the last commit as:
https://github.com/alfg/opendrinks/pull/721/commits/ca1d472c70fe01e4f33f9533f0a77038b4dfccd8

However, the image itself doesn't seem to be checked in.

2020-10-04 20:07 UTC, xtbe commented
Thanks, so it looks like the image needs to be attached, thought it could be externally referenced. I will submit a new PR. Thank you for clarifying