Mariposa
alfg/opendrinks pull request #726
Opened 2020-10-01 02:04 UTC by nathaniellers

Hacktoberfest!

2020-10-01 02:13 UTC, alfg requested changes
Added suggested to correct image path. Thanks!

2020-10-01 02:13 UTC, alfg commented on src/recipes/mariposa-drink.json
> +    "image": "mariposa,jpg",
```suggestion
    "image": "mariposa.jpg",
```

2020-10-01 02:14 UTC, nathaniellers commented on src/recipes/mariposa-drink.json
> +    "image": "mariposa,jpg",
oh.. sorry. Thanks!

2020-10-01 02:48 UTC, alfg requested changes
Two more fixes suggested. Also, can you keep the image size below 200KB, please? Thanks!

2020-10-01 02:48 UTC, alfg commented on src/recipes/dalogna-coffee.json
> +    "image": "mariposa.jpg",
```suggestion
    "image": "dalgona-coffee.jpg",
```

2020-10-01 02:48 UTC, alfg commented on src/recipes/dalogna-coffee.json
> +    "name": "Dalogna Coffee",
This should be `Dalgona Coffee`, right?

2020-10-04 19:59 UTC, alfg commented
Closing. As dalgona coffee conflicts with existing recipe. Feel free to re-open another with the fixed Mariposa recipe. Thanks.

2020-10-04 19:59 UTC, closed without merging