Add Indonesian Beverage
alfg/opendrinks pull request #741
Opened 2020-10-01 13:53 UTC by KangAbbad

2020-10-01 17:51 UTC, alfg requested changes
Added few suggestions. Thanks.

2020-10-01 17:51 UTC, alfg commented on src/recipes/wedang-uwuh.json
> +    "github": "@KangAbbad",
```suggestion
    "github": "KangAbbad",
```

2020-10-01 17:51 UTC, alfg commented on src/recipes/wedang-uwuh.json
> +        },
```suggestion
        }
```

2020-10-01 17:51 UTC, alfg commented on src/recipes/wedang-uwuh.json
> +        "javanese",
```suggestion
        "javanese"
```

2020-10-02 08:39 UTC, KangAbbad commented
> Added few suggestions. Thanks.

2020-10-06 01:54 UTC, alfg commented
Closing as this conflicts with another recipe added recently.

2020-10-06 01:54 UTC, closed without merging