Add recipe 'Diana's lips'
alfg/opendrinks pull request #789
Opened 2020-10-03 10:38 UTC by lucasmartinelle

2020-10-03 20:26 UTC, alfg requested changes
Couple suggestions. Thanks.

2020-10-03 20:26 UTC, alfg commented on src/recipes/dianas-lips.json
> +        "Mezcal"
Can we lowercase these?

2020-10-03 20:26 UTC, alfg commented on src/recipes/dianas-lips.json
> +    "description": "a cocktail based on mezcal infused with cocoa beans and pink berries, lime and Schweppes Tonic Hibiscus",
```suggestion
    "description": "A cocktail based on mezcal infused with cocoa beans and pink berries, lime and Schweppes Tonic Hibiscus.",

```

2020-10-04 19:50 UTC, lucasmartinelle commented
done

2020-10-04 19:55 UTC, merged

2020-10-04 19:55 UTC, alfg commented
Thanks!