add recipe 'Coco Loco'
alfg/opendrinks pull request #790
Opened 2020-10-03 11:23 UTC by lucasmartinelle

2020-10-03 20:28 UTC, alfg requested changes
I think this was branched from your last PR. So I can't merge until the last one is merged/approved. I also added a couple suggestions. Thanks.

2020-10-03 20:28 UTC, alfg commented on src/recipes/coco-loco.json
> +        "Alcohol",
```suggestion
        "alcohol",

```

2020-10-03 20:28 UTC, alfg commented on src/recipes/coco-loco.json
> +    "description": "a rum and coconut cocktail from the West Indies",
```suggestion
    "description": "A rum and coconut cocktail from the West Indies.",

```

2020-10-04 19:50 UTC, lucasmartinelle commented
done :)

2020-10-04 19:57 UTC, alfg commented
Hi, I think you'll need to sync up this branch with latest from master in order for the updated changeset to show. And to resolve conflict.

2020-10-05 18:10 UTC, closed without merging