detox-green-tea
alfg/opendrinks pull request #792
Opened 2020-10-03 17:09 UTC by aindrila2412

2020-10-03 17:18 UTC, aindrila2412 commented
I request a maintainer to accept my PR by adding "hacktoberfest-accepted" label to it.

2020-10-03 20:18 UTC, alfg requested changes
Hi, added a few suggestions to fix valid json. Thanks!

2020-10-03 20:18 UTC, alfg commented on detox-green-tea.json
> +        },
```suggestion
        }
```

2020-10-03 20:18 UTC, alfg commented on detox-green-tea.json
> +        "leaves"
Missing commas for valid json.

2020-10-03 20:18 UTC, alfg commented on detox-green-tea.json
> +        "Add remaining water in jar, and mix well."
Missing commas for valid json.

2020-10-05 13:38 UTC, aindrila2412 commented on detox-green-tea.json
>  }
Hey, I have resolved the issue.
Can you please check it and approve my PR with Hacktoberfest label

2020-10-06 01:50 UTC, alfg commented
Hi @aindrila2412, 

Thanks for the update. However, the JSON still seems to be invalid. Try running it through a validator, such as https://json.pizza to highlight the issues.

2020-10-06 02:00 UTC, alfg requested changes
See recent comment. Thanks.

2020-10-06 21:56 UTC, alfg requested changes
The recipe JSON goes into `src/recipes/` and images go into `src/assets/recipes/` folders respectively. Thanks.

2020-10-07 08:23 UTC, closed without merging