Add Fall Old-Fashioned
alfg/opendrinks pull request #808
Opened 2020-10-04 18:16 UTC by s-Hale

2020-10-04 19:42 UTC, alfg requested changes
Hi, can you rename the image to match the recipe?
`fall-old-fashioned.jpg`.

2020-10-04 23:31 UTC, alfg requested changes

2020-10-04 23:31 UTC, alfg commented on src/recipes/fall-old-fashioned.json
> +    "github": "shale",
Is this the right user?

2020-10-05 09:31 UTC, s-Hale commented on src/recipes/fall-old-fashioned.json
> +    "github": "shale",
Sorry, needs a hyphen. Fixed.

2020-10-06 01:51 UTC, merged

2020-10-06 01:51 UTC, alfg commented
Thanks!