Added bentley
alfg/opendrinks pull request #813
Opened 2020-10-04 21:19 UTC by ludoo0d0a

Added the bentley cocktail ;)

2020-10-04 23:33 UTC, alfg requested changes

2020-10-04 23:33 UTC, alfg commented on src/recipes/bentley.json
> +    "description": "This coktail invented in 1920's in London, refers to the famous brand of luxe car. It is referenced in Savoy Cocktail Book from 1930. The legend says that the Bentley Boys (rich a
```suggestion
    "description": "This cocktail invented in 1920's in London, refers to the famous brand of luxe car. It is referenced in Savoy Cocktail Book from 1930. The legend says that the Bentley Boys (rich and famous British drivers) invented this drink after a win at 24h Le Mans.",
```

2020-10-04 23:33 UTC, alfg commented on src/recipes/bentley.json
> +        "Dubonnet",
```suggestion
        "dubonnet",
```

2020-10-08 05:52 UTC, alfg commented
Closing. Feel free to re-open with suggested fixes. Thanks!

2020-10-08 05:52 UTC, closed without merging

2020-10-08 07:18 UTC, ludoo0d0a commented
I cannot fix, in this PR because it's closed ; I will submit a new one with suggested fixes.
unless you reopen this PR :)