Add Watermelon Moscow Mule
alfg/opendrinks pull request #849
Opened 2020-10-10 17:58 UTC by Sina-Sche

Fix small bugs in my json file, hopefully all is going to work now 👍

2020-10-10 20:37 UTC, alfg requested changes
Added a few suggested fixes. Thanks.

2020-10-10 20:37 UTC, alfg commented on src/recipes/watermelon-moscow-mule.json
> +        "ingredient": "Mint leaves"}
```suggestion
        "ingredient": "Mint leaves"},
```

2020-10-10 20:37 UTC, alfg commented on src/recipes/watermelon-moscow-mule.json
> +        "ingredient": "Ice cubes"}
```suggestion
        "ingredient": "Ice cubes"},
```

2020-10-10 20:37 UTC, alfg commented on src/recipes/watermelon-moscow-mule.json
> +    "image": "<watermelon-moscow-mule.jpg>",
```suggestion
    "image": "watermelon-moscow-mule.jpg",
```

2020-10-10 20:37 UTC, alfg commented on src/recipes/watermelon-moscow-mule.json
> +        "vodka",
```suggestion
        "vodka"
```

2020-10-11 11:42 UTC, Sina-Sche commented
> Added a few suggested fixes. Thanks.

Thanks a lot!!!

2020-10-11 19:51 UTC, merged

2020-10-11 19:51 UTC, alfg commented
Looks good. Thanks for fixing!