Added Basil Kadha
alfg/opendrinks pull request #853
Opened 2020-10-11 13:46 UTC by somesh-ops

2020-10-11 19:52 UTC, alfg requested changes
Image seems to be missing from this PR. Also added a suggested fix for the invalid json.

2020-10-11 19:52 UTC, alfg commented on src/recipes/basil-kadha.json
> +        "Strain and serve hot.",
```suggestion
        "Strain and serve hot."
```

2020-10-12 06:19 UTC, alfg requested changes
Please add the image. Thanks.

2020-10-12 14:38 UTC, somesh-ops commented
> 
> 
> Please add the image. Thanks.

@alfg : Added, please review.

2020-10-12 20:25 UTC, alfg commented
@somesh-ops can you remove the image from the old/invalid location?

2020-10-13 06:27 UTC, somesh-ops commented
> 
> 
> @somesh-ops can you remove the image from the old/invalid location?

@alfg removed invalid upload, please review.

2020-10-13 07:06 UTC, merged

2020-10-13 07:06 UTC, alfg commented
Thanks!