Added orange-earl-grey-iced-tea
alfg/opendrinks pull request #857
Opened 2020-10-11 17:54 UTC by sujoy-coder

Nice and cool project!
Hopefully you like my contribution and add it, If so please add `hacktoberfest-accepted` tag. 

Thank You :)

2020-10-11 19:56 UTC, alfg requested changes
Hi @sujoy-coder, I added a suggested fix for the image path in the JSON file. Also, please provide an image that isn't stretched as 600x400px in size. Thanks.

2020-10-11 19:56 UTC, alfg commented on src/recipes/orange-earl-grey-iced-tea.json
> +    "image": "<drink-name.jpg>",
```suggestion
    "image": "orange-earl-grey-iced-tea.jpg",
```

2020-10-12 04:33 UTC, alfg commented
Hi @sujoy-coder, the image still appears to be stretched. Can you provide an image while maintaining the aspect ratio?

2020-10-12 05:53 UTC, sujoy-coder commented
@alfg sir, I don't understand what is happening although I make the image 600x400 px dimension as mentioned. So I make it 600x600 px . Now check it pls...

Thank You...

2020-10-12 06:16 UTC, merged

2020-10-12 06:16 UTC, alfg commented
This is fine. Thank you!

2020-10-12 06:26 UTC, sujoy-coder commented
Thank You....sir :)