Created Rysgaard's Corona Special drink
alfg/opendrinks pull request #951
Opened 2020-10-26 15:21 UTC by Crowton

2020-10-26 19:06 UTC, alfg requested changes
Hi, can you also use lowercase and hyphens in the filenames only? The JSON and image file should match.

```
rysgaards-corona-special.jpg
rysgaards-corona-special.json
```

Thanks.

2020-10-26 19:06 UTC, alfg commented on src/recipes/rysgaardsCoronaSpecial.json
> +        "Old Danish"
lowercase please

2020-10-26 19:06 UTC, alfg commented on src/recipes/rysgaardsCoronaSpecial.json
> +    "github": "https://github.com/Crowton",
```suggestion
    "github": "Crowton",
```

2020-10-26 19:06 UTC, alfg commented on src/recipes/rysgaardsCoronaSpecial.json
> +    "description": "A drink for drinking alone in your appartment when quarentined.",
```suggestion
    "description": "A drink for drinking alone in your apartment when quarantined.",
```

2020-10-26 19:06 UTC, alfg commented on src/recipes/rysgaardsCoronaSpecial.json
> +        "If there is too much alcohol in the drink, you can always cry in it, to lower the percentage"
😆

2020-10-26 19:15 UTC, Crowton commented
> Hi, can you also use lowercase and hyphens in the filenames only? The JSON and image file should match.
> 
> ```
> rysgaards-corona-special.jpg
> rysgaards-corona-special.json
> ```
> 
> Thanks.

Sure

2020-10-27 01:03 UTC, alfg commented on src/recipes/rysgaards-corona-special.json
> +    "image": "rysgaardSpecial.jpg",
```suggestion
    "image": "rysgaards-corona-special.jpg",
```

2020-10-27 08:29 UTC, merged

2020-10-27 08:29 UTC, alfg commented
Thanks!