The Bengal Tiger
alfg/opendrinks pull request #956
Opened 2020-10-27 00:06 UTC by ch1771dr0b0

2020-10-27 01:00 UTC, alfg requested changes
Hi, can you find a horizontal image close to 600x400px in size? Also, please use hyphens, instead of the underscores. Thanks.

2020-10-27 03:06 UTC, ch1771dr0b0 commented
> Hi, can you find a horizontal image close to 600x400px in size? Also, please use hyphens, instead of the underscores. Thanks.

completed the changes

2020-10-27 03:09 UTC, alfg commented on src/recipes/the-bengal-tiger.json
> +    "image": "the_bengal_tiger.jpg",
Need to update here as well.

2020-10-27 18:26 UTC, ch1771dr0b0 reviewed
completed the changes to json file.

2020-10-27 18:27 UTC, ch1771dr0b0 commented on src/recipes/the-bengal-tiger.json
> +    "image": "the_bengal_tiger.jpg",
change image name in json file.

2020-10-28 00:00 UTC, alfg commented
> 
> 
> > Hi, can you find a horizontal image close to 600x400px in size? Also, please use hyphens, instead of the underscores. Thanks.
> 
> completed the changes

Hi, the image doesn't seem to be horizontal.

2020-10-28 13:05 UTC, ch1771dr0b0 commented
> > > Hi, can you find a horizontal image close to 600x400px in size? Also, please use hyphens, instead of the underscores. Thanks.
> > 
> > 
> > completed the changes
> 
> Hi, the image doesn't seem to be horizontal.

changes completed.

2020-10-29 01:10 UTC, alfg commented
> 
> 
> > > > Hi, can you find a horizontal image close to 600x400px in size? Also, please use hyphens, instead of the underscores. Thanks.
> > > 
> > > 
> > > completed the changes
> > 
> > 
> > Hi, the image doesn't seem to be horizontal.
> 
> changes completed.

Please provide a horizontal image. This one is still vertical.

2020-10-29 02:34 UTC, ch1771dr0b0 commented
> > > > > Hi, can you find a horizontal image close to 600x400px in size? Also, please use hyphens, instead of the underscores. Thanks.
> > > > 
> > > > 
> > > > completed the changes
> > > 
> > > 
> > > Hi, the image doesn't seem to be horizontal.
> > 
> > 
> > changes completed.
> 
> Please provide a horizontal image. This one is still vertical.

Uploa

> > > > > Hi, can you find a horizontal image close to 600x400px in size? Also, please use hyphens, instead of the underscores. Thanks.
> > > > 
> > > > 
> > > > completed the changes
> > > 
> > > 
> > > Hi, the image doesn't seem to be horizontal.
> > 
> > 
> > changes completed.
> 
> Please provide a horizontal image. This one is still vertical.

Uploaded new image. Please verify.

2020-10-29 03:47 UTC, merged

2020-10-29 03:47 UTC, alfg commented
This is good. Thanks!