Add grilled grapefruit paloma cocktail recipe
alfg/opendrinks pull request #963
Opened 2020-10-27 21:12 UTC by ferdox2

fix #882 
Adds grilled grapefruit paloma cocktail recipe.

2020-10-28 00:04 UTC, alfg requested changes

2020-10-28 00:04 UTC, alfg commented on src/recipes/grilled-grapefruit-paloma-cocktail.json
> +        },
```suggestion
        {
            "quantity": "2",
            "measure": "",
            "ingredient": "Limes"
        },
```

2020-10-28 00:04 UTC, alfg commented on src/recipes/grilled-grapefruit-paloma-cocktail.json
> +        },
```suggestion
        {
            "quantity": "1",
            "measure": "",
            "ingredient": "Red grapefruit, halved widthwise"
        },
```

2020-10-28 00:31 UTC, ferdox2 commented on src/recipes/grilled-grapefruit-paloma-cocktail.json
> +        },
done

2020-10-28 00:31 UTC, ferdox2 commented on src/recipes/grilled-grapefruit-paloma-cocktail.json
> +        },
done

2020-10-29 03:50 UTC, merged

2020-10-29 03:50 UTC, alfg commented
Thanks!