nannari sarabath recipe
alfg/opendrinks pull request #987
Opened 2020-10-29 07:47 UTC by saikoushalg

2020-10-29 08:21 UTC, alfg requested changes
Can you use hyphens instead of the spaces in the filenames?

2020-10-29 08:24 UTC, saikoushalg commented
> 
> 
> Can you use hyphens instead of the spaces in the filenames?

okay

2020-10-29 08:36 UTC, alfg commented
Please use hyphens instead of spaces. For example:
```
nannari-sarabath.json
nannari-sarabath.jpg
```

Thanks.

2020-10-29 08:43 UTC, alfg commented
And also remove the old files. There should only be 2 files in this PR. Thanks!

2020-10-29 08:43 UTC, saikoushalg commented
> 
> 
> And also remove the old files. There should only be 2 files in this PR. Thanks!

okay thanks!

2020-10-30 04:59 UTC, alfg requested changes

2020-10-30 04:59 UTC, alfg commented on src/recipes/nannari-sarabath.json
> +
Remove empty lines.

2020-10-30 04:59 UTC, alfg commented on src/recipes/nannari-sarabath.json
> +        " let it Cool down completely and add lemon juice",
Empty leading space and capitalization, please.

2020-10-30 04:59 UTC, alfg commented on src/recipes/nannari-sarabath.json
> +
Empty line.

2020-10-30 05:33 UTC, alfg commented
Hmm, I'm not seeing the corrections. Can you check?

2020-11-02 01:21 UTC, merged