Add the recipe for the Raspberry Caipirinha
alfg/opendrinks pull request #991
Opened 2020-10-29 10:24 UTC by Mayie

Add one of my favourite cocktail: Raspberry Caipirinha !

2020-10-29 22:14 UTC, alfg requested changes

2020-10-29 22:14 UTC, alfg commented on src/recipes/raspberry-caipirinha.json
> +    "image": "Raspberry-Caipirihna.jpg",
```suggestion
    "image": "raspberry-caipirihna.jpg",
```

2020-10-29 22:14 UTC, alfg commented on src/recipes/raspberry-caipirinha.json
> +    "source": "https://www.kcet.org/sites/kl/files/atoms/article_atoms/www.kcet.org/living/food/assets/images/Mo-chica-Raspadilla%2520Caiprinha1.jpg",
Link to the source page of the recipe, rather than the image. Or you can remove this line if none provided.

2020-10-31 01:27 UTC, alfg requested changes
Seems like the image filename is misspelled.

2020-10-31 05:00 UTC, kazuhirodk commented on src/recipes/raspberry-caipirinha.json
> +        "Raspberry"
Use lowercase for keywords
```suggestion
        "cachaca",
        "raspberry"
```

2020-10-31 05:02 UTC, kazuhirodk commented on src/recipes/raspberry-caipirinha.json
> +
These newlines is unnecessary
```suggestion
```

2020-10-31 05:04 UTC, kazuhirodk commented on src/recipes/raspberry-caipirinha.json
> +    "ingredients": [
All ingredient itens indentation isn't correct. Add a tab/space for all block and remove all empty lines,

2020-10-31 05:04 UTC, kazuhirodk commented on src/recipes/raspberry-caipirinha.json
> +
```suggestion
```

2020-10-31 05:05 UTC, kazuhirodk commented on src/recipes/raspberry-caipirinha.json
> +
```suggestion
    ],
```

2020-10-31 05:07 UTC, kazuhirodk commented on src/recipes/raspberry-caipirinha.json
> +
Unnecessary line
```suggestion
```

2020-10-31 15:44 UTC, Mayie commented
Thank you for the review, can you check again ?

2020-10-31 20:27 UTC, merged

2020-10-31 20:27 UTC, alfg commented
Thanks @Mayie!