Added sweet-lassi recipe
alfg/opendrinks pull request #993
Opened 2020-10-29 12:14 UTC by sayalitandel

Hey @alfg! Please check my contribution. I've participated in the hacktoberfest for the first time. I would be glad if you would merge the PR and label it as hacktoberfest-accepted. Thank you!

2020-10-29 22:17 UTC, alfg requested changes
Couple of suggestions. Thanks.

2020-10-29 22:17 UTC, alfg commented on src/recipes/sweet-lassi.json
> +    "name": "Lassi",
```suggestion
    "name": "Sweet Lassi",
```

2020-10-29 22:17 UTC, alfg commented on src/recipes/sweet-lassi.json
> +    "image": "<sweet-lassi.jpg>",
```suggestion
    "image": "sweet-lassi.jpg",
```

2020-10-30 10:43 UTC, sayalitandel commented
Hey @alfg! I have made suggested changes. Please review it. I would be glad if you would merge the PR and label it as hacktoberfest-accepted. Thank you!

2020-10-31 01:28 UTC, merged

2020-10-31 01:28 UTC, alfg commented
Thanks for fixing!