adding a new recipe
alfg/opendrinks pull request #994
Opened 2020-10-29 15:33 UTC by xhalin01

adding a new recipe for alien brain hemorrhage

2020-10-29 22:19 UTC, alfg requested changes
Nice one! Lol. I left 2 suggestions before we can merge. Thanks.

2020-10-29 22:19 UTC, alfg commented on src/recipes/alien-brain-hemorrhage.json
> +    "name": "Alien brain hemorrhage",
```suggestion
    "name": "Alien Brain Hemorrhage",

```

2020-10-29 22:19 UTC, alfg commented on src/recipes/alien-brain-hemorrhage.json
> +    "source": "<source url if available, otherwise remove this line>",
```suggestion
```

Can remove this line if no source provided.

2020-10-30 07:07 UTC, xhalin01 commented
Thanks for your suggestions, I updated the source and name of the drink. It should be ready to **merge**.

2020-10-30 07:40 UTC, merged

2020-10-30 07:47 UTC, alfg commented
Thank you!

2020-10-30 07:49 UTC, xhalin01 commented
> Thank you!

You are welcome.